name: Deploying docker image 

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: building docker image
     run: |
       docker build ./ -t mying 
      
   - uses: docker/build-push-action@v1
   - name: Build and push docker image
     with:
      username: 
      password: 
      
        
   
